
services:
  web:
    build: .
    container_name: ProScout-web
    ports:
      - "8003:8003"
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8003", "--reload"]
