services:
  web:
    build: .
    container_name: Scoutlyze-web
    restart: always
    ports:
      - "8003:8003"
    volumes:
      - .:/app
    env_file:
      - .env
    command: /bin/sh -c "./entrypoint.sh"
